version: '3'

networks:
  docker_env:
    driver: bridge

services:
  influxdb:
    image: ${INFLUXDB_IMAGE}
    restart: always
    container_name: influxdb
    hostname: influxdb
    ports:
      - 8086:8086
    volumes:
      - "${INFLUXDB_DIR}/etc:/etc/influxdb"
      - "${INFLUXDB_DIR}/data:/var/lib/influxdb/data"
      - "${INFLUXDB_DIR}/meta:/var/lib/influxdb/meta"
      - "${INFLUXDB_DIR}/wal:/var/lib/influxdb/wal"
    environment:
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD:-influx_admin_default_pass}"
    networks:
      - docker_env
  influxui:
    image: ${INFLUXUI_IMAGE}
    restart: always
    container_name: influxui
    hostname: influxui
    ports:
      - 3001:80
  redis:
    image: ${REDIS_IMAGE}
    restart: always
    container_name: redis
    hostname: redis
    ports:
      - 8900:6379
    volumes:
      - "${REDIS_DIR}/data:/data"
    command:
      redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis_default_pass}
    networks:
      - docker_env
  mysql:
    image: ${MYSQL_IMAGE}
    restart: always
    container_name: mysql
    hostname: mysql
    ports:
      - 8306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysql_root_default_pass}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"
      - "${MYSQL_DIR}/config:/etc/mysql/conf.d"
    networks:
      - docker_env
